name: flutter_base
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.3+3

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.5.0

  # Networking & API
  dio: ^5.3.2
  http: ^1.1.0
  pretty_dio_logger: ^1.4.0

  # Caching & Storage
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.1
  shared_preferences: ^2.2.1
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  path: ^1.8.3

  # UI Components & Styling
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.16
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.8.0
  modal_bottom_sheet: ^3.0.0
  flutter_easyloading: ^3.0.5
  table_calendar: ^3.0.9

  # Documents & Files
  flutter_pdfview: ^1.4.0
  syncfusion_flutter_pdfviewer: ^28.2.3
  file_picker: ^9.0.2
  image_picker: ^1.1.2

  # Utilities
  intl: ^0.18.1
  package_info_plus: ^8.3.0
  uuid: ^4.5.1
  permission_handler: ^12.0.0+1
  fl_chart: ^0.71.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # Testing
  mockito: ^5.4.4
  mocktail: ^1.0.3
  network_image_mock: ^2.0.1

  # Code Generation
  build_runner: ^2.4.8
  riverpod_generator: ^2.5.0

  # Code Quality
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Assets for the app
  assets:
    - assets/images/
